version: 1.0.{build}
os: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
nuget:
  project_feed: true
before_build:
- cmd: nuget restore -DisableParallelProcessing Sources/EpicMorg-Supervisor.sln
build:
  parallel: true
  verbosity: normal
